import { Lightbulb, CheckCircle2, AlertCircle, Sparkles, Cpu, Quote } from 'lucide-react'

export default function SuggestionsList({ aiAnalysis, analyzer }) {
  if (!aiAnalysis) return null
  const isAi = analyzer === 'gemini'

  const wrapperCls = isAi
    ? 'card p-6 relative overflow-hidden border-accent/30 bg-gradient-to-br from-accent/5 via-white to-purple-50/40'
    : 'card p-6 relative overflow-hidden border-ink-200 bg-white'

  return (
    <div className={wrapperCls}>
      {isAi && (
        <div className="absolute -top-16 -right-16 w-48 h-48 rounded-full bg-accent/10 blur-3xl pointer-events-none" />
      )}

      <div className="relative flex items-center justify-between gap-2 mb-2">
        <div className="flex items-center gap-2">
          {isAi ? (
            <Sparkles size={18} className="text-accent" />
          ) : (
            <Cpu size={18} className="text-ink-500" />
          )}
          <h3 className="font-display text-lg font-semibold text-ink-900">
            {isAi ? 'Gemini AI Insights' : 'Heuristic Insights'}
          </h3>
          <span
            className={`ml-1 inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold border ${
              isAi
                ? 'bg-accent/15 text-accent-dark border-accent/30'
                : 'bg-ink-100 text-ink-600 border-ink-200'
            }`}
          >
            {isAi ? 'AI-generated' : 'Rule-based'}
          </span>
        </div>
        {isAi && (
          <span className="hidden sm:inline text-[11px] text-ink-500">
            Powered by Google Gemini
          </span>
        )}
      </div>

      {aiAnalysis.summary && (
        <div
          className={`relative mb-5 p-3.5 rounded-lg text-sm leading-relaxed flex gap-2.5 ${
            isAi
              ? 'bg-white/70 border border-accent/20 text-ink-800'
              : 'bg-ink-50 border border-ink-200 text-ink-700'
          }`}
        >
          <Quote size={14} className={`mt-0.5 shrink-0 ${isAi ? 'text-accent' : 'text-ink-400'}`} />
          <p className="italic">{aiAnalysis.summary}</p>
        </div>
      )}

      <div className="relative grid md:grid-cols-3 gap-5">
        <Section title="Strengths" icon={CheckCircle2} color="success"
          items={aiAnalysis.strengths || []} emptyText="No specific strengths identified." isAi={isAi} />
        <Section title="Issues" icon={AlertCircle} color="warning"
          items={aiAnalysis.issues || []} emptyText="No issues found. Nice!" isAi={isAi} />
        <Section title="Suggestions" icon={Lightbulb} color="accent"
          items={aiAnalysis.suggestions || []} emptyText="No improvements needed." isAi={isAi} />
      </div>

      {!isAi && (
        <div className="relative mt-5 pt-4 border-t border-ink-100 text-[11px] text-ink-500 flex items-center gap-1.5">
          <Cpu size={11} />
          Generated by deterministic rules. Toggle <span className="font-semibold">Gemini AI</span> in
          Settings for richer, context-aware insights.
        </div>
      )}
    </div>
  )
}

function Section({ title, icon: Icon, color, items, emptyText, isAi }) {
  const colorMap = {
    success: 'text-success bg-success/10',
    warning: 'text-warning bg-warning/10',
    accent: 'text-accent-dark bg-accent/10',
  }
  const itemBg = isAi ? 'bg-white/60 border-accent/10' : 'bg-ink-50 border-ink-100'
  return (
    <div>
      <div className="flex items-center gap-2 mb-3">
        <div className={`w-7 h-7 rounded-lg grid place-items-center ${colorMap[color]}`}>
          <Icon size={14} />
        </div>
        <div className="font-semibold text-sm text-ink-900">{title}</div>
        <div className="text-xs text-ink-400 ml-auto">{items.length}</div>
      </div>
      {items.length ? (
        <ul className="space-y-2">
          {items.map((item, i) => (
            <li key={i}
              className={`text-sm text-ink-700 leading-relaxed flex gap-2 px-2.5 py-2 rounded-md border ${itemBg}`}>
              <span className="text-ink-400 shrink-0">•</span>
              <span>{item}</span>
            </li>
          ))}
        </ul>
      ) : (
        <div className="text-xs text-ink-400 italic">{emptyText}</div>
      )}
    </div>
  )
}
